server:
  port: 8089

spring:
  application:
    name: statement-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/statement_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.transactsphere.statement: DEBUG
