apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: REDIS_HOST
              value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: REDIS_HOST
              value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: account-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: REDIS_HOST
              value: "redis"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: transaction-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_AUTH
              value: "true"
            - name: MAIL_STARTTLS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
spec:
  selector:
    app: fraud-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
    spec:
      containers:
        - name: fraud-service
          image: fraud-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: analytics-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: audit-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: statement-service
spec:
  selector:
    app: statement-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statement-service
  template:
    metadata:
      labels:
        app: statement-service
    spec:
      containers:
        - name: statement-service
          image: statement-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: DB_HOST
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: admin-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - secretRef:
                name: banking-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
